// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhauiFK-61CNnOMBdFSjaFrAIFGhe1vcY',
    appId: '1:754605637180:web:9c4d89c8ee02b8cdd30d39',
    messagingSenderId: '754605637180',
    projectId: 'milesoft-chat',
    authDomain: 'milesoft-chat.firebaseapp.com',
    storageBucket: 'milesoft-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogtXVw_WT6NWiQ3Bnz2o9qBE1rH4yUKQ',
    appId: '1:754605637180:android:6940383ca30b8f12d30d39',
    messagingSenderId: '754605637180',
    projectId: 'milesoft-chat',
    storageBucket: 'milesoft-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeS2pYYrjvqbK2hFGw1PET3RzLf4Y41aM',
    appId: '1:754605637180:ios:b70b038b42f00ba6d30d39',
    messagingSenderId: '754605637180',
    projectId: 'milesoft-chat',
    storageBucket: 'milesoft-chat.appspot.com',
    iosBundleId: 'africa.milesoft.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeS2pYYrjvqbK2hFGw1PET3RzLf4Y41aM',
    appId: '1:754605637180:ios:b70b038b42f00ba6d30d39',
    messagingSenderId: '754605637180',
    projectId: 'milesoft-chat',
    storageBucket: 'milesoft-chat.appspot.com',
    iosBundleId: 'africa.milesoft.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhauiFK-61CNnOMBdFSjaFrAIFGhe1vcY',
    appId: '1:754605637180:web:e97aebfb0a76d77ad30d39',
    messagingSenderId: '754605637180',
    projectId: 'milesoft-chat',
    authDomain: 'milesoft-chat.firebaseapp.com',
    storageBucket: 'milesoft-chat.appspot.com',
  );
}
